services:
  - name: autoscale-example-web
    type: web
    env: ruby
    buildCommand: bin/render-build.sh
    startCommand: bundle exec rails server
    envVars:
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 0
      - key: RAILS_MAX_THREADS
        value: 1
      - key: REDIS_URL
        fromService:
          type: redis
          name: autoscale-example-redis
          property: connectionString

  - name: autoscale-example-worker
    type: worker
    env: ruby
    plan: starter
    buildCommand: bundle install
    startCommand: "bundle exec sidekiq -q urgent -q default"
    envVars:
      # RAILS_MAX_THREADS configures Sidekiq concurrency (and the DB pool if we're using a database)
      - key: RAILS_MAX_THREADS
        value: 1
      - key: REDIS_URL
        fromService:
          type: redis
          name: autoscale-example-redis
          property: connectionString

  - name: autoscale-example-redis
    type: redis
    ipAllowList: [] # only allow connections from services in this Render account
